import { Problem } from '@/types'

export const PROBLEMS: Problem[] = [
  {
    slug: 'oily-skin',
    title: 'Oily Skin & Large Pores',
    emoji: '🫧',
    shortDesc: 'Shiny face, makeup doesn\'t stay, feels dirty all day',
    fullDesc: 'Overactive sebaceous glands produce excess sebum, leading to a shiny appearance, clogged pores, and frequent breakouts. Humidity and genetics make it worse for most Indians.',
    cause: 'Overactive sebaceous glands triggered by hormones, humidity, or genetics.',
    badge: 'Very Common',
    badgeColor: 'gold',
    compounds: [
      { name: 'Niacinamide', reason: 'Signals skin to produce less oil. Visible results in 4 weeks.' },
      { name: 'Salicylic Acid', reason: 'Oil-soluble — penetrates and cleans deep inside pores.' },
      { name: 'Zinc PCA', reason: 'Regulates sebum at the skin cell level. Works synergistically with Niacinamide.' },
      { name: 'Kaolin Clay', reason: 'Physically absorbs excess oil without stripping moisture.' },
    ],
  },
  {
    slug: 'acne',
    title: 'Acne & Pimples',
    emoji: '🔴',
    shortDesc: 'Painful breakouts affecting confidence and daily life',
    fullDesc: 'Acne forms when pores get clogged with dead skin cells and sebum, creating an environment where bacteria thrive. Inflammation makes it red and painful. Very treatable with the right ingredients.',
    cause: 'Clogged pores + C. acnes bacteria + inflammation response.',
    badge: 'High Concern',
    badgeColor: 'coral',
    compounds: [
      { name: 'Salicylic Acid', reason: 'Dissolves the plug inside pores. Best for blackheads and active pimples.' },
      { name: 'Benzoyl Peroxide', reason: 'Directly kills acne-causing bacteria inside pores. Fast acting.' },
      { name: 'Niacinamide', reason: 'Reduces redness and fades post-acne marks after breakouts heal.' },
      { name: 'Tea Tree Oil', reason: 'Natural antibacterial — good for mild acne without dryness.' },
    ],
  },
  {
    slug: 'pigmentation',
    title: 'Pigmentation & Dark Spots',
    emoji: '🟤',
    shortDesc: 'Dark marks left by pimples, uneven skin tone',
    fullDesc: 'Post-inflammatory hyperpigmentation occurs when skin overproduces melanin after inflammation (pimples, cuts). Sun exposure makes it darker and harder to fade. Very common in Indian skin tones.',
    cause: 'Excess melanin triggered by inflammation, UV exposure, or hormones.',
    badge: 'Very Common',
    badgeColor: 'gold',
    compounds: [
      { name: 'Alpha Arbutin', reason: 'Targets melanin production at the source. Gentler and safer than hydroquinone.' },
      { name: 'Vitamin C', reason: 'Brightens existing spots and prevents UV-triggered new ones.' },
      { name: 'Kojic Acid', reason: 'Natural melanin inhibitor derived from fungi. Works on stubborn deep spots.' },
      { name: 'Niacinamide', reason: 'Prevents melanin from reaching skin surface, evens overall tone.' },
    ],
  },
  {
    slug: 'hair-fall',
    title: 'Hair Fall & Thinning',
    emoji: '💇',
    shortDesc: 'Excessive shedding during wash, brushing, or on pillow',
    fullDesc: 'Losing 50–100 hairs per day is normal. Beyond that, causes include nutrient deficiency, DHT sensitivity (genetic), stress, or weak follicles. The good news — most types are very treatable.',
    cause: 'Weak follicles, DHT sensitivity, nutrient deficiency, or scalp inflammation.',
    badge: 'Treatable',
    badgeColor: 'sage',
    compounds: [
      { name: 'Redensyl', reason: 'Clinically proven to reactivate dormant hair follicles. Works better than Minoxidil for many.' },
      { name: 'Caffeine', reason: 'Blocks DHT at scalp level and stimulates follicle growth locally.' },
      { name: 'Biotin', reason: 'Strengthens the hair shaft and reduces breakage from root.' },
      { name: 'Procapil', reason: 'Anchors hair to follicle and improves scalp circulation.' },
    ],
  },
  {
    slug: 'dark-circles',
    title: 'Dark Circles',
    emoji: '🌑',
    shortDesc: 'Tired-looking eyes even after full sleep',
    fullDesc: 'Dark circles appear when thin under-eye skin reveals blood vessels underneath, or when melanin deposits accumulate. Dehydration and genetics are major factors in Indian skin.',
    cause: 'Thin skin showing blood vessels + pigmentation + dehydration.',
    badge: 'High Concern',
    badgeColor: 'coral',
    compounds: [
      { name: 'Caffeine', reason: 'Constricts blood vessels and visibly reduces puffiness within hours.' },
      { name: 'Peptides', reason: 'Thickens thin under-eye skin over time, hiding blood vessels below.' },
      { name: 'Vitamin K', reason: 'Strengthens capillaries and reduces the bluish-dark discolouration.' },
      { name: 'Hyaluronic Acid', reason: 'Plumps hollow under-eye area, reducing shadow-based darkness.' },
    ],
  },
  {
    slug: 'dry-skin',
    title: 'Dry & Dehydrated Skin',
    emoji: '🌵',
    shortDesc: 'Flaky patches, tight feeling, rough and dull skin',
    fullDesc: 'Dry skin lacks oil (lipids). Dehydrated skin lacks water. Both cause tightness, flakiness, and a dull appearance. A compromised skin barrier is usually the root cause.',
    cause: 'Damaged skin barrier losing moisture + insufficient lipid production.',
    badge: 'Very Common',
    badgeColor: 'sage',
    compounds: [
      { name: 'Hyaluronic Acid', reason: 'Draws water into skin — holds up to 1000x its weight in moisture.' },
      { name: 'Ceramides', reason: 'Rebuilds the skin barrier that keeps moisture locked in.' },
      { name: 'Glycerin', reason: 'Humectant that pulls moisture from air into skin layers.' },
      { name: 'Squalane', reason: 'Lightweight oil that mimics skin\'s own sebum — no greasiness.' },
    ],
  },
  {
    slug: 'dandruff',
    title: 'Dandruff & Itchy Scalp',
    emoji: '❄️',
    shortDesc: 'White flakes, itching, and embarrassing scalp buildup',
    fullDesc: 'Dandruff is caused by a fungus (Malassezia) that feeds on scalp oils and causes irritation and rapid skin cell turnover. Very common, especially in humid Indian weather.',
    cause: 'Malassezia fungus overgrowth on oily scalps triggering inflammation.',
    badge: 'Treatable',
    badgeColor: 'sage',
    compounds: [
      { name: 'Zinc Pyrithione', reason: 'Most proven antifungal for dandruff. Kills Malassezia directly.' },
      { name: 'Ketoconazole', reason: 'Prescription-strength antifungal for stubborn dandruff cases.' },
      { name: 'Salicylic Acid', reason: 'Exfoliates buildup and flakes from scalp surface.' },
      { name: 'Tea Tree Oil', reason: 'Natural antifungal that soothes itchy, irritated scalp.' },
    ],
  },
  {
    slug: 'sun-tan',
    title: 'Sun Tan & UV Damage',
    emoji: '☀️',
    shortDesc: 'Uneven tan lines, patchy skin, darker than natural tone',
    fullDesc: 'UV rays trigger melanin production as a defense mechanism. Repeated exposure without protection leads to permanent tanning, uneven patches, and accelerated skin aging.',
    cause: 'UV radiation triggering excess melanin production and skin cell damage.',
    badge: 'Preventable',
    badgeColor: 'coral',
    compounds: [
      { name: 'SPF 50 Sunscreen', reason: 'The single most important product — prevents ALL types of UV damage.' },
      { name: 'Vitamin C', reason: 'Reverses existing UV damage and inhibits new melanin formation.' },
      { name: 'Kojic Acid', reason: 'Removes existing tan by inhibiting melanin at production stage.' },
      { name: 'Lactic Acid', reason: 'Gently exfoliates tanned surface skin cells to reveal brighter skin.' },
    ],
  },
]

export function getProblemBySlug(slug: string): Problem | undefined {
  return PROBLEMS.find(p => p.slug === slug)
}